name: Crawl IQAir Data

on:
  schedule:
    - cron: '0 */1 * * *'  
  workflow_dispatch:  

jobs:
  crawl-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}  
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r weather-dataset/requirements.txt
          playwright install chromium
        
      - name: Run crawler
        run: python weather-dataset/crawl_iqair.py
      
      - name: Pull latest changes from remote
        run: |
          git fetch origin
          git reset --hard origin/master

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add weather-dataset/result/*
          git diff --staged --quiet || git commit -m "Update data [skip ci]"
          git push origin master
